name: updater
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - fastapi=0.103.0
  - idna=3.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - python=3.12.3
  - readline=8.2
  - setuptools=69.5.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.27.0
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
